data:
  input_shape: [32, 32, 3]
  num_classes: 10
  batch_size: 32

model:
  conv_filters: [32, 64, 128]
  kernel_size: 3
  pool_size: 2
  dropout_rate: 0.3
  dense_units: [128, 64]
  dense_dropout_rate: 0.5

training:
  epochs: 50
  initial_learning_rate: 0.001
  monitor: val_loss
  patience: 5
  min_delta: 0.001

augmentation:
  enabled: true
  rotation_range: 0.2
  zoom_range: 0.2
  flip_mode: horizontal
